"""Document upload service: presigned S3 URLs and document inventory management.

Design §9.2: uploaded documents land in incoming/{application_id}/ with
a document_id sub-path.  The document_id is assigned here and recorded
in the application's document_inventory before returning the URL.

The presigned PUT URL is generated by S3Repository and scoped to the
exact S3 key and Content-Type so the client cannot overwrite other paths.
"""

import logging
import uuid
from datetime import UTC, datetime

from fastapi import HTTPException
from shared.schemas import ApplicationStatus, Document

from backend.core.settings import Settings
from backend.repositories.s3_repository import S3Repository
from backend.schemas.application_schema import (
    DocumentUploadRequest,
    PresignedUploadResponse,
)
from backend.services.application_service import ApplicationService

log = logging.getLogger(__name__)

_UPLOAD_CONTENT_TYPE = "application/pdf"
_INCOMING_KEY_TEMPLATE = "incoming/{application_id}/{document_id}.pdf"

_UPLOADABLE_STATUSES = {ApplicationStatus.PENDING}


class DocumentService:
    """Issues presigned S3 PUT URLs and tracks documents in the application inventory."""

    def __init__(
        self,
        s3: S3Repository,
        application_service: ApplicationService,
        settings: Settings,
    ) -> None:
        self._s3 = s3
        self._app_svc = application_service
        self._settings = settings

    async def create_presigned_upload(
        self,
        application_id: str,
        request: DocumentUploadRequest,
    ) -> PresignedUploadResponse:
        """Validate application state, mint a presigned PUT URL, update inventory.

        Steps:
          1. Load the application and assert it is in a state that allows uploads.
          2. Assign a document_id and build the target S3 key.
          3. Generate a presigned PUT URL scoped to that key + Content-Type.
          4. Append a Document record to the application's inventory and persist.
          5. Return the upload details to the caller.

        Args:
            application_id: The application to attach the document to.
            request:        Document type selection from the caller.

        Returns:
            PresignedUploadResponse with upload_url, s3_key, and expiry.

        Raises:
            HTTPException(404): if the application does not exist.
            HTTPException(409): if the application is not in an uploadable state.
        """
        app = await self._app_svc.get_application(application_id)

        if app.status not in _UPLOADABLE_STATUSES:
            raise HTTPException(
                status_code=409,
                detail=(
                    f"Documents cannot be uploaded to an application in '{app.status}' status. "
                    "Only PENDING applications accept document uploads."
                ),
            )

        document_id = f"doc_{uuid.uuid4().hex}"
        s3_key = _INCOMING_KEY_TEMPLATE.format(
            application_id=application_id,
            document_id=document_id,
        )

        upload_url = await self._s3.generate_presigned_put(
            key=s3_key,
            content_type=_UPLOAD_CONTENT_TYPE,
            expires_in=self._settings.presigned_url_ttl_seconds,
        )

        doc = Document(
            document_id=document_id,
            application_id=application_id,
            document_type=request.document_type,
            s3_key=s3_key,
            uploaded_at=datetime.now(UTC),
            parse_status="PENDING",
        )
        app.document_inventory.append(doc)
        await self._app_svc.update_application(app)

        log.info(
            "Presigned upload URL issued",
            extra={
                "application_id": application_id,
                "document_id": document_id,
                "document_type": str(request.document_type),
                "s3_key": s3_key,
            },
        )

        return PresignedUploadResponse(
            **{
                "documentId": document_id,
                "uploadUrl": upload_url,
                "s3Key": s3_key,
                "contentType": _UPLOAD_CONTENT_TYPE,
                "expiresInSeconds": self._settings.presigned_url_ttl_seconds,
            }
        )
